name: ecommerce_final_task
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  badges: ^3.1.2
  carousel_slider: ^4.2.1
  dartz: ^0.10.1
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fluttertoast: ^8.2.3
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.1
  animated_notch_bottom_bar: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true

  assets:
    - assets/png/
    - assets/jpg/
    - assets/svg/
